# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eYLCgRRA5XTPkJx6uZ4AYi7D_8qscWF5
"""

!pip install streamlit

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
import streamlit as st
import joblib

from google.colab import drive
drive.mount('/content/drive')

# Import the dataset
file_dir = "/content/drive/MyDrive/TUGAS AKHIR/airlines_flights_data.csv.xls" # Sesuaikan!
df = pd.read_csv(file_dir)
# Read Dataset
display(df)

# load
model = joblib.load('/content/drive/MyDrive/TUGAS AKHIR/model.pkl')
columns = joblib.load('/content/drive/MyDrive/TUGAS AKHIR/columns.pkl')

st.title("✈️ Flight Price Prediction")

# INPUT
duration = st.number_input("Duration", min_value=0.0)
days_left = st.number_input("Days Left", min_value=0)

class_type = st.selectbox("Class", ["Economy", "Business"])
stops = st.selectbox("Stops", ["zero", "one", "two_or_more"])

departure_time = st.selectbox(
    "Departure Time",
    ["Early_Morning", "Morning", "Afternoon", "Evening", "Night", "Late_Night"]
)

arrival_time = st.selectbox(
    "Arrival Time",
    ["Early_Morning", "Morning", "Afternoon", "Evening", "Night", "Late_Night"]
)

airline = st.text_input("Airline")
source_city = st.text_input("Source City")
destination_city = st.text_input("Destination City")

# mapping
class_map = {'Economy': 0, 'Business': 1}
stops_map = {'zero': 0, 'one': 1, 'two_or_more': 2}
time_map = {
    'Early_Morning': 0, 'Morning': 1, 'Afternoon': 2,
    'Evening': 3, 'Night': 4, 'Late_Night': 5
}

if st.button("Predict"):

    data = {
        'duration': duration,
        'days_left': days_left,
        'class': class_map[class_type],
        'stops': stops_map[stops],
        'departure_time': time_map[departure_time],
        'arrival_time': time_map[arrival_time]
    }

    df_input = pd.DataFrame([data])

    # ONE HOT MANUAL
    for col in columns:
        if col not in df_input.columns:
            df_input[col] = 0

    if f'airline_{airline}' in columns:
        df_input[f'airline_{airline}'] = 1

    if f'source_city_{source_city}' in columns:
        df_input[f'source_city_{source_city}'] = 1

    if f'destination_city_{destination_city}' in columns:
        df_input[f'destination_city_{destination_city}'] = 1

    df_input = df_input[columns]

    pred = model.predict(df_input)[0]

    st.success(f"💰 Harga: {pred:,.0f}")

